### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by NormanPerrin** [syntax-tree/nlcst-to-string#4]
When parsing an image node the length assignment breaks.

This is how the node looks like:
```javascript
{
    alt: "img description"
    position: Position {start: {…}, end: {…}, indent: Array(0)}
    title: null
    type: "image"
    url: "/img/…"
}
```

And it breaks here:
```javascript
children = 'length' in node ? node : node.children
length = children.length
```

As children is undefined.

A posible solution could be just add an if validation for the undefined children and return an empty array. Don't know if it's the appropriate thing to do.
```javascript
children = 'length' in node ? node : node.children
if(!children) return ''
length = children.length
```

**Comment by ChristianMurphy** [comment]
`image` isn"t a nlcst node type. https://github.com/syntax-tree/nlcst
Could you provide sample code/config/content?

**Comment by wooorm** [comment]
@NormanPerrin Hi there, thanks for the question and welcome to unified!

What you are passing is an [mdast](https://github.com/syntax-tree/mdast) node, not as Christian points out an [nlcst](https://github.com/syntax-tree/nlcst) node.

As we’re dealing with mdast, you can fix this issue by using [`mdast-util-to-string`](https://github.com/syntax-tree/mdast-util-to-string).
